"""add orders 4

Revision ID: 39551de7c0e1
Revises: b8518deadf27
Create Date: 2023-10-04 17:43:38.992345

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Union, Sequence


# revision identifiers, used by Alembic.
revision: str = '39551de7c0e1'
down_revision: Union[str, None] = 'b8518deadf27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'time')
    # ### end Alembic commands ###
