"""add orders 2

Revision ID: 3c7da6edec5b
Revises: 55414d1bbf45
Create Date: 2023-10-04 17:39:46.089904

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Union, Sequence

# revision identifiers, used by Alembic.
revision: str = '3c7da6edec5b'
down_revision: Union[str, None] = '55414d1bbf45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('transaction_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'approved')
    op.drop_column('orders', 'transaction_code')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
