"""added added time

Revision ID: 8916ab248cd4
Revises: af64ef7b1be8
Create Date: 2023-10-05 10:55:12.528035

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Union, Sequence


# revision identifiers, used by Alembic.
revision: str = '8916ab248cd4'
down_revision: Union[str, None] = 'af64ef7b1be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('day', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'day')
    op.drop_column('orders', 'time')
    # ### end Alembic commands ###
