"""added relation to seat to order

Revision ID: abfa150c3679
Revises: 4cb0a8792fa8
Create Date: 2023-10-05 18:22:14.719729

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Union, Sequence


# revision identifiers, used by Alembic.
revision: str = 'abfa150c3679'
down_revision: Union[str, None] = '4cb0a8792fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
