"""added remove time

Revision ID: af64ef7b1be8
Revises: 25d99840431c
Create Date: 2023-10-05 10:52:24.062358

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Union, Sequence
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af64ef7b1be8'
down_revision: Union[str, None] = '25d99840431c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
