"""added relation to seat to order rev1

Revision ID: b0b7398d540f
Revises: abfa150c3679
Create Date: 2023-10-05 18:22:59.765793

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Union, Sequence


# revision identifiers, used by Alembic.
revision: str = 'b0b7398d540f'
down_revision: Union[str, None] = 'abfa150c3679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
