"""added default created at

Revision ID: e671bcf44cad
Revises: 39551de7c0e1
Create Date: 2023-10-05 07:38:03.155261

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from typing import Union, Sequence

# revision identifiers, used by Alembic.
revision: str = 'e671bcf44cad'
down_revision: Union[str, None] = '39551de7c0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'time')
    op.add_column('seats', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('tables', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'price')
    op.drop_column('seats', 'price')
    op.add_column('orders', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
