"""added relation to user and order

Revision ID: eff25a5b8ce5
Revises: 6b8e58f615ef
Create Date: 2023-10-05 18:16:26.753123

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Union, Sequence


# revision identifiers, used by Alembic.
revision: str = 'eff25a5b8ce5'
down_revision: Union[str, None] = '6b8e58f615ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
